name: "Godot Web Export & Deploy"

on:
  push:
    branches:
      - main

jobs:
  export_web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup Godot Templates
        run: |
          mkdir -v -p ~/.local/share/godot/build_templates
          mv /root/.local/share/godot/templates/* ~/.local/share/godot/build_templates/

      - name: Create Web Build Directory
        run: mkdir -v -p build/web

      - name: Export Web
        run: godot --headless --export-release "Web" build/web/index.html

      - name: Deploy to GitHub Pages
        uses: Peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
